use customer_behaviour
select top 5 * from customer_behaviour 
--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total from customer_behaviour group by gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount,discount_applied  from customer_behaviour where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer_behaviour)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(avg(review_rating),2) as rating from customer_behaviour group by item_purchased order by rating desc)

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount) as salary,shipping_type from customer_behaviour where shipping_type in ('Standard','Express') group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(*) as frequency,avg(purchase_amount) as average,sum(purchase_amount)as total from customer_behaviour group by subscription_status 

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,(sum(purchase_amount)/count(item_purchased))*100 as percentage from customer_behaviour where discount_applied ='Yes' group by item_purchased order by percentage desc


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as(select customer_id,case when previous_purchases<=1 then 'New'
            when previous_purchases>=2 and previous_purchases<=10 then 'Returning'
            else 'Loyal' end as segment from customer_behaviour )
select segment,count(*) as total from cte group by segment order by total desc
--Q8. What are the top 3 most purchased products within each category? 
 with prod as (select item_purchased,count(customer_id) as total,category,row_number() over(partition by category order by count(customer_id) desc) as rnk from customer_behaviour group by category,item_purchased) 
 select  * from prod where rnk<=3 

 select purchase_amount,item_purchased,category from customer_behaviour group by category
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select customer_id,previous_purchases,subscription_status from customer_behaviour where previous_purchases>5 and subscription_status in ('Yes')
--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue from customer_behaviour group by age_group